name: Coverage

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
          node-version: ${{ matrix.node-version }}

      - run: pnpm install
      - run: pnpm test:cov
